language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary_daotest;'
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql

services:
  - mysql

install:
  - "sudo apt-get install mysql-common mysql-server-5.5.25 mysql-server-core-5.5.25 mysql-client-5.5.25 mysql-client-core-5.5.25"