language: java

jdk:
  - oraclejdk8

services:
  - mysql

dist: trusty

sudo: required

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

addons:
  apt:
    packages:
      - oracle-java8-installer
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary_daotest;'
  - mysql -u root -e "CREATE USER 'stas'@'localhost' IDENTIFIED BY 'stas';"
  - mysql -u root -e "GRANT ALL ON diary.* TO 'stas'@'localhost';"
  - mysql -u root -e "GRANT ALL ON diary_daotest.* TO 'stas'@'localhost';"
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/ADMIN_TABLE_26_12.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/CATEGORY_TABLE_26_12.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/ADMIN_TABLE_26_12.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/CATEGORY_TABLE_26_12.sql
  - mysql -u root -e "SHOW DATABASES;"
  - mysql -u root -e "SHOW TABLES FROM diary;"
  - mysql -u root -e "SHOW TABLES FROM diary_daotest;"
  - mysql -u root diary_daotest < INSERT INTO admin (id, admin_name, admin_password) VALUES(1, 'admin', '0dea849e9fe91b89b411440f4cc0ae0f');

script: ./gradlew check --info