language: java

jdk:
  - oraclejdk8

services:
  - mysql

dist: trusty

sudo: required

branches:
  only:
    - master

before_install:
  - chmod +x gradlew

addons:
  apt:
    packages:
        - oracle-java8-installer
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS diary_daotest;'

  - mysql -u root -e "CREATE USER 'root'@'localhost' IDENTIFIED BY 'root';"
  - mysql -u root -e "GRANT ALL ON diary.* TO 'root'@'localhost';"
  - mysql -u root -e "GRANT ALL ON diary_daotest.* TO 'root'@'localhost';"

  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql
  - mysql -u root diary < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/ADMIN_TABLE_26-12-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/USER_TABLE_20-11-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/EVENT_TABLE_18-12-16.sql
  - mysql -u root diary_daotest < /home/travis/build/exZStas/diary/pp-backend/src/main/resources/db/migration/ADMIN_TABLE_26-12-16.sql