CREATE TABLE `event` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  `DESCRIPTION` varchar(200) DEFAULT NULL,
  `CATEGORY` varchar(45) NOT NULL,
  `COMPLEXITY` bit(1) NOT NULL,
  `START_TIME` date NOT NULL,
  `END_TIME` date NOT NULL,
  `DURATION` int(11) NOT NULL,
  `DONE_STATUS` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`,`USER_ID`),
  KEY `USER_ID_idx` (`USER_ID`),
  CONSTRAINT `USER_ID` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);