CREATE TABLE `diary`.`user` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NOT NULL,
  `LAST_NAME` VARCHAR(45) NOT NULL,
  `GENDER` VARCHAR(1) NULL,
  `STUDY_GROUP` VARCHAR(10) NOT NULL,
  `BIRTHDAY` DATE NULL,
  `EMAIL` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`));
