CREATE TABLE `PRACTICE` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `AGB` varchar(45) NOT NULL,
  `NAME` varchar(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `AGB_UNIQUE` (`AGB`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `USER` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRACTICE_ID` int(11) NOT NULL,
  `BSN` varchar(45) NOT NULL,
  `FIRST_NAME` varchar(45) NOT NULL,
  `LAST_NAME` varchar(45) NOT NULL,
  `MIDDLE_NAME` varchar(45) DEFAULT NULL,
  `EMAIL` varchar(255) NOT NULL,
  `GENDER` varchar(10) DEFAULT NULL,
  `BIRTHDATE` datetime DEFAULT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `PATIENT_NUMBER` varchar(60) DEFAULT NULL,
  `WEBLINK_ID` varchar(60) DEFAULT NULL,
  `REG_STATUS` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `BSN_UNIQUE` (`BSN`),
  UNIQUE KEY `EMAIL_UNIQUE` (`EMAIL`),
  UNIQUE KEY `PATIENT_NUMBER_UNIQUE` (`PATIENT_NUMBER`),
  UNIQUE KEY `WEBLINK_ID_UNIQUE` (`WEBLINK_ID`),
  KEY `USER_PRACTICE_FK_idx` (`PRACTICE_ID`),
  CONSTRAINT `USER_PRACTICE_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;

CREATE TABLE `ADMIN` (
  `ID` int(11) NOT NULL,
  `LOGIN` varchar(45) NOT NULL,
  `PASSWORD` varchar(45) NOT NULL,
  `PRACTICE_ID` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `LOGIN_UNIQUE` (`LOGIN`),
  KEY `ADMIN_PRACTICE_FK_IDX` (`PRACTICE_ID`),
  CONSTRAINT `ADMIN_PRACTICE_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;

CREATE TABLE `DAILY_STATISTIC` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PRACTICE_ID` int(11) NOT NULL,
  `DATE` datetime NOT NULL,
  `ATTRIBUTE` varchar(50) NOT NULL,
  `DAILY_COUNT` int(11) NOT NULL,
  `TOTAL_COUNT` int(11) NOT NULL,
  PRIMARY KEY (`ID`),
  KEY `DAILY_STATISTIC_PRACTICE_FK_idx` (`PRACTICE_ID`),
  CONSTRAINT `DAILY_STATISTIC_PRACTICE_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;

CREATE TABLE `ECONSULT` (
  `ECONSULT_ID` int(10) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `AGB` varchar(45) NOT NULL,
  `STATUS` varchar(45) NOT NULL,
  PRIMARY KEY (`ECONSULT_ID`),
  KEY `ECONSULT_USER_FK_idx` (`USER_ID`),
  CONSTRAINT `ECONSULT_USER_FK` FOREIGN KEY (`USER_ID`)  REFERENCES `USER` (`ID`)  ON DELETE NO ACTION  ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;

CREATE TABLE `HOLIDAY_PRACTICE_MESSAGE` (
  `PRACTICE_ID` int(11) NOT NULL,
  `MESSAGE` varchar(4000) DEFAULT NULL,
  `ECONSULT` tinyint(1) NOT NULL DEFAULT '0',
  `AFSPRAAK` tinyint(1) NOT NULL DEFAULT '0',
  `PRESCRIPTION` tinyint(1) NOT NULL DEFAULT '0',
  `START_DATE_HOLIDAY` datetime NOT NULL,
  `END_DATE_HOLIDAY` datetime NOT NULL,
  PRIMARY KEY (`PRACTICE_ID`),
  CONSTRAINT `HOLIDAY_PRACTICE_MESSAGE_PRACTICE_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;

CREATE TABLE `MAIL_NOTIFICATION` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `MAIL_TEMPLATE_TYPE` varchar(100) NOT NULL,
  `FROM_MAIL` varchar(100) NOT NULL,
  `TO_MAIL` varchar(100) NOT NULL,
  `SUBJECT` varchar(500) NOT NULL,
  `BODY` mediumtext NOT NULL,
  `ATTEMPTS` int(1) NOT NULL,
  `DATE_TO_SEND` datetime NOT NULL,
  `STATUS` varchar(100) NOT NULL,
  PRIMARY KEY (`ID`)
) DEFAULT CHARSET=utf8;

CREATE TABLE `MAIL_TEMPLATE` (
  `PRACTICE_ID` int(11) NOT NULL,
  `TYPE` varchar(45) NOT NULL,
  `CONTENT` mediumblob NOT NULL,
  PRIMARY KEY (`PRACTICE_ID`,`TYPE`),
  CONSTRAINT `MAIL_TEMPLATE_PRACTICE_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;

CREATE TABLE `PAGE_CONTENT` (
  `PRACTICE_ID` int(11) NOT NULL,
  `PAGE_NAME` varchar(50) NOT NULL,
  `TEXT` varchar(2000) NOT NULL,
  PRIMARY KEY (`PRACTICE_ID`,`PAGE_NAME`),
  KEY `PRACTICE_ID_FK_idx` (`PRACTICE_ID`),
  CONSTRAINT `PRACTICE_ID_FK` FOREIGN KEY (`PRACTICE_ID`) REFERENCES `PRACTICE` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) DEFAULT CHARSET=utf8;
